Bet.destroy_all
Participation.destroy_all
Team.destroy_all
Match.destroy_all
UserReward.destroy_all
Reward.destroy_all
User.destroy_all
Squad.destroy_all

squad = Squad.create!(name: "Les Boss")
user_1 = User.create!(email: "azerty@gmail.com", password: "azerty", nickname: "Gégédu33",points_counter:300, squad: squad)
user_2 = User.create!(email: "azerto@gamil.com", password: "azerto", nickname: "MBappé", squad: squad )

barcelone = Team.create!(name: "FC Barcelone", sport: "Football")
madrid = Team.create!(name: "Real Madrid", sport: "Football")
psg = Team.create!(name: "PSG", sport: "Football")
om = Team.create!(name: "OM", sport: "Football")
lorient = Team.create!(name: "FC Lorient", sport: "Football")
rennes = Team.create!(name: "Rennes FC", sport: "Football")
los_angeles = Team.create!(name: "Los Angeles Dodgers", sport: "Baseball")
boston = Team.create!(name: "Boston Red Sox", sport: "Baseball")
lyon = Team.create!(name: "OL", sport: "Baseball")
monaco = Team.create!(name: "Monaco", sport: "Baseball")
chelsea = Team.create!(name: "Chelsea FC", sport: "Football")
manchester_u = Team.create!(name: "Manchester United", sport: "Football")
liverpool = Team.create!(name: "Liverpool", sport: "Football")
manchester_city = Team.create!(name: "Manchester City", sport: "Football")
milan_ac = Team.create!(name: "Milan AC", sport: "Football")
rome = Team.create!(name: "AS Roma", sport: "Football")
inter = Team.create!(name: "Inter Milan", sport: "football")
juventus = Team.create!(name: "Juventus Turin", sport: "Football")
benfica = Team.create!(name: "Benfica Lisbonne", sport: "Baseball")
porto = Team.create!(name: "FC Porto", sport: "Baseball")
inde = Team.create!(name: "Inde", sport: "Criquet")
australie = Team.create!(name: "Australie", sport: "Criquet")

match_1 = Match.create!(sport: "Football", date: Date.tomorrow, funbet: false)
match_2 = Match.create!(sport: "Football", date: Date.tomorrow, funbet: false)
match_3 = Match.create!(sport: "Football", date: Date.tomorrow, funbet: false)
match_4 = Match.create!(sport: "baseball", date: Date.tomorrow, funbet: true)
match_5 = Match.create!(sport: "football", date: Date.tomorrow, funbet: false)
match_6 = Match.create!(sport: "Football", date: Date.yesterday, funbet: false)
match_7 = Match.create!(sport: "Football", date: Date.yesterday, funbet: false)
match_8 = Match.create!(sport: "Football", date: Date.yesterday, funbet: false)
match_9 = Match.create!(sport: "football", date: Date.yesterday, funbet: false)
match_10 = Match.create!(sport: "football", date: Date.yesterday, funbet: false)
match_11 = Match.create!(sport: "cricket", date: Date.yesterday, funbet: true)

participation_1 = Participation.create!(team: barcelone, match: match_1, odd: 1.7)
participation_2 = Participation.create!(team: madrid, match: match_1, odd: 2)
participation_3 = Participation.create!(team: psg, match: match_2, odd: 2)
participation_4 = Participation.create!(team: om, match: match_2, odd: 1.8)
participation_5 = Participation.create!(team: lorient, match: match_3, odd: 3)
participation_6 = Participation.create!(team: rennes, match: match_3, odd: 2)
participation_7 = Participation.create!(team: los_angeles, match: match_4, odd: 1.8)
participation_8 = Participation.create!(team: boston, match: match_4, odd: 2)
participation_9 = Participation.create!(team: lyon, match: match_5, odd: 2.5)
participation_10 = Participation.create!(team: monaco, match: match_5, odd: 1.7)
participation_11 = Participation.create!(team: chelsea, match: match_6, odd: 2.1, score: 3)
participation_12 = Participation.create!(team: manchester_u, match: match_6, odd: 2.3, score: 1)
participation_13 = Participation.create!(team: liverpool, match: match_7, odd: 2, score: 2)
participation_14 = Participation.create!(team: manchester_city, match: match_7, odd: 1.8, score: 2)
participation_15 = Participation.create!(team: milan_ac, match: match_8, odd: 2, score: 2)
participation_16 = Participation.create!(team: rome, match: match_8, odd: 3, score: 0)
participation_17 = Participation.create!(team: inter, match: match_9, odd: 1.8, score: 1)
participation_18 = Participation.create!(team: juventus, match: match_9, odd: 2, score: 1)
participation_19 = Participation.create!(team: benfica, match: match_10, odd: 2.5, score: 3)
participation_20 = Participation.create!(team: porto, match: match_10, odd: 1.7, score: 3)
participation_21 = Participation.create!(team: inde, match: match_11, odd: 2.5, score: 240)
participation_22 = Participation.create!(team: australie, match: match_11, odd: 1.7, score: 241)

reward_1 = Reward.create!(title: "Panenka!", description: "points doublés au prochain pari", price: 200)
reward_2 = Reward.create!(title: "Poteau rentrant", description: "+100 points au prochain pari gagné", price: 50)
reward_3 = Reward.create!(title: "Coup du chapeau", description: "+200 points", price: 250)
reward_4 = Reward.create!(title: "Tacle à la gorge", description: "points au cube", price: 350)

bet_1 = Bet.create!(user: user_1, participation: participation_12, progress: 0, match: match_6)
bet_2 = Bet.create!(user: user_2, participation: participation_1, progress: 0, match: match_7)
bet_3 = Bet.create!(user: user_1, progress: 0, match: match_9)
bet_4 = Bet.create!(user: user_2, participation: participation_18, progress: 0, match: match_9)
bet_5 = Bet.create!(user: user_2, participation: participation_19, progress: 0, match: match_10)
bet_6 = Bet.create!(user: user_1, progress: 0, match: match_11)
